# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 318042b549721d6c0ac14c9483c6e1e43e11aae2fb994f68a1a7d6284a8ba848d210f9f7f4bab4ba90e4373d06d176a1e4edcfbabd8392616ba021d3c5da03a4

test:
  secret_key_base: 9b3123563d154c92c582a3d85dbfeba36ee11139c1f0be7d4638e575db37826550f306d31ac801fee61ea3f34ea028cb1e297d8d75faa45f37377e004e43c70c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
